##===================================================================================================
##                 Copyright 2015   NumScale SAS
##
##                   Distributed under the Boost Software License, Version 1.0.
##                        See accompanying file LICENSE.txt or copy at
##                            http://www.boost.org/LICENSE_1_0.txt
##===================================================================================================
sudo: false
language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: CXX_STD=11 TOOLSET=g++-4.8 SIMD_EXT=-mavx OPT=-ftrack-macro-expansion=0

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.8']
      env: CXX_STD=11 TOOLSET=g++-4.8 SIMD_EXT=-msse4.1 OPT=-ftrack-macro-expansion=0

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-4.9']
      env: CXX_STD=11 TOOLSET=g++-4.9 SIMD_EXT=-mavx OPT=-ftrack-macro-expansion=0

    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5']
      env: CXX_STD=11 TOOLSET=g++-5 SIMD_EXT=-mavx OPT=-ftrack-macro-expansion=0

# Prepare build
before_script:
  - export BOOST_ROOT=build/_install/include
  - mkdir build
  - cd build
  - cmake .. -DIS_TRAVIS_CI= -DCMAKE_CXX_COMPILER=$TOOLSET -DCMAKE_CXX_FLAGS="$SIMD_EXT $OPT -I$HOME/dispatch/include" -DSIMD_EXT=$SIMD_EXT -DCXX_STD=$CXX_STD -DTOOLSET=$TOOLSET

# Build unit and run test
script:
  - make update.boost-header-only | grep -v "^-- " # Silent installation
  - make  -j 4 -k  regression.unit
  - ctest -j 4 -R ^regression.*.unit
  - make  -j 4 -k  api.unit
  - ctest -j 4 -R ^api.*.unit
  - make  -j 4 -k  architecture.unit
  - ctest -j 4 -R ^architecture.*.unit
  - make  -j 4 -k  function.simd.unit
  - ctest -j 4 -R ^function.simd.*.unit
  - make  -j 4 -k  constant.simd.unit
  - ctest -j 4 -R ^constant.simd.*.unit
  - make  -j 4 -k  function.scalar.unit
  - ctest -j 4 -R ^function.scalar.*.unit
  - make  -j 4 -k  constant.scalar.unit
  - ctest -j 4 -R ^constant.scalar.*.unit
